-- =============================================
-- E-Cell Advertisement Popup System
-- Database Setup for Advertisements Table
-- =============================================

-- Create advertisements table
CREATE TABLE IF NOT EXISTS public.advertisements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    image_url text NOT NULL,
    event_id bigint REFERENCES public.events(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'inactive' CHECK (status IN ('active', 'inactive')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create updated_at trigger function if it doesn't exist
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
DROP TRIGGER IF EXISTS handle_advertisements_updated_at ON public.advertisements;
CREATE TRIGGER handle_advertisements_updated_at
    BEFORE UPDATE ON public.advertisements
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- =============================================
-- Row Level Security (RLS) Policies
-- =============================================

-- Enable RLS on advertisements table
ALTER TABLE public.advertisements ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read access to active advertisements only
CREATE POLICY "Public users can view active advertisements" ON public.advertisements
    FOR SELECT USING (status = 'active');

-- Policy: Allow authenticated users (admins) full access
CREATE POLICY "Authenticated users can manage advertisements" ON public.advertisements
    FOR ALL USING (auth.role() = 'authenticated');

-- =============================================
-- Indexes for Performance
-- =============================================

-- Index for status queries (most common query)
CREATE INDEX IF NOT EXISTS idx_advertisements_status ON public.advertisements(status);

-- Index for event_id foreign key
CREATE INDEX IF NOT EXISTS idx_advertisements_event_id ON public.advertisements(event_id);

-- Index for created_at ordering
CREATE INDEX IF NOT EXISTS idx_advertisements_created_at ON public.advertisements(created_at DESC);

-- =============================================
-- Sample Data (Optional - for testing)
-- =============================================

-- Insert a sample advertisement (uncomment to use)
-- INSERT INTO public.advertisements (title, image_url, event_id, status) 
-- VALUES (
--     'Sample Advertisement',
--     'https://via.placeholder.com/400x500/0066cc/ffffff?text=Sample+Ad',
--     1, -- Replace with actual event ID
--     'inactive'
-- );

-- =============================================
-- Verification Queries
-- =============================================

-- Check if table was created successfully
SELECT 
    table_name, 
    column_name, 
    data_type, 
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'advertisements' 
ORDER BY ordinal_position;

-- Check RLS policies
SELECT 
    schemaname,
    tablename,
    policyname,
    permissive,
    roles,
    cmd,
    qual
FROM pg_policies 
WHERE tablename = 'advertisements';

-- Check indexes
SELECT 
    indexname,
    indexdef
FROM pg_indexes 
WHERE tablename = 'advertisements';

-- =============================================
-- Usage Notes
-- =============================================

/*
IMPORTANT RULES:
1. Only ONE advertisement should have status = 'active' at a time
2. The frontend will always fetch the latest active advertisement
3. When activating a new ad, deactivate all others first
4. Image aspect ratio should be 4:5 (validated in frontend)
5. event_id can be NULL if the ad doesn't link to an event

ADMIN WORKFLOW:
1. Create advertisement with status = 'inactive'
2. Upload/set image_url (4:5 aspect ratio)
3. Link to event (optional)
4. Activate advertisement (this should deactivate others)

FRONTEND BEHAVIOR:
- Fetch active advertisement on every page load
- Show popup if active advertisement exists
- Redirect to event details when clicked (if event_id exists)
- Always show popup (no localStorage/cookies dependency)
*/